version: '3'

services:
  varnish:
    build: .
    image: jonbaldie/varnish
    ports:
      - "80:80"
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    depends_on:
      - web
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  web:
    image: nginx:alpine
    restart: unless-stopped
